project_name: taon
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
release:
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
      - '^test:'
      - '^ci:'
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Refactorings'
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999
brews:
  - name: taon
    tap:
      owner: eiri
      name: homebrew-tap
    commit_author:
      name: eiri
      email: eiri@eiri.ca
    commit_msg_template: "feat: brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    homepage: "https://github.com/eiri/taon"
    description: "Transform JSON into ASCII table"
    license: "MIT"
