name: build
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'
        check-latest: true
        cache: true
    - name: Run tests
      run: go test -v ./pkg/taon/...
      env:
        CGO_ENABLED: 0

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'
        check-latest: true
        cache: true
    - name: Make build
      run: go build -ldflags "-s -w -X main.version=$VERSION" ./cmd/taon/...
      env:
        VERSION: v0.0.0
    - name: Check build
      shell: bash
      run: "echo '{\"int\": 1, \"str\": \"one\", \"bool\": true}' | ./taon"
