name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: Run tests
      run: go test -v ./pkg/taon/...
      env:
        CGO_ENABLED: 0

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: Make build
      run: go build -ldflags "-s -w -X main.version=$VERSION" ./cmd/taon/...
      env:
        VERSION: v0.0.0
    - name: Check build
      shell: bash
      run: "echo '{\"int\": 1, \"str\": \"one\", \"bool\": true}' | ./taon"
