name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --force --tags
      - name: Setup go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
          check-latest: true
          cache: true
      - name: Build release
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_HOMEBREW_PAT: ${{ secrets.GH_HOMEBREW_PAT }}
