name: test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.18', '1.19']
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup go ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
        check-latest: true
        cache: true
    - name: Run tests
      run: go test -v ./pkg/taon/...
